version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sky12345
      POSTGRES_DB: Todo
    ports:
      - "5432:5432"
